### ISSUE TITLE
Add Documentation with regards to the project .

### ISSUE THREAD

**Issue by rishi-kai** [rishi-kai/Smart-Traffic-Management-System#1]
Projects's main problem statement and core issues that it is dealing with .

**Comment by serenchi-oz** [comment]
hey , i was interested in this issue would you let me work on this please

**Comment by rishi-kai** [comment]
what sort of additions can you make to the documentation?

**Comment by serenchi-oz** [comment]
Basically what is the core problem that the project is addressing and how it tends to tackle the problem

**Comment by rishi-kai** [comment]
sure ! let me know if any help is needed :)
