### ISSUE TITLE
Dataset Documentation

### ISSUE THREAD

**Issue by rishi-kai** [rishi-kai/Smart-Traffic-Management-System#5]
I'm working on  a datset , for whom i need some documentation that a lay man can understand about the dataset

**Comment by serenchi-oz** [comment]
Sure , ive just checked the dataset would love to add a file documenting it , here are some additions im interested in:Content
This dataset contains 48.1k (48120) observations of the number of vehicles each hour in four different junctions:

1. DateTime
2. Junction
3.  Vehicles
4.ID

**Comment by rishi-kai** [comment]
there are some notable changes in the documentation im interested in , well lets see how it turns up:)
